// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_n_J8QjDifPrYRBxuG4fCzjczO4JXrAA',
    appId: '1:1063253896672:web:3f02c3dd69d64fa9538f85',
    messagingSenderId: '1063253896672',
    projectId: 'appointment-system-91352',
    authDomain: 'appointment-system-91352.firebaseapp.com',
    storageBucket: 'appointment-system-91352.firebasestorage.app',
    measurementId: 'G-FR8KDNWQL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGiUrUMC2crkzDknVivasIxCq8xpFMfU0',
    appId: '1:1063253896672:android:cad9aa7505acadc6538f85',
    messagingSenderId: '1063253896672',
    projectId: 'appointment-system-91352',
    storageBucket: 'appointment-system-91352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ZLV8KvjVy8uqaqlYSacpGH_1r_evu-k',
    appId: '1:1063253896672:ios:229716693be405a3538f85',
    messagingSenderId: '1063253896672',
    projectId: 'appointment-system-91352',
    storageBucket: 'appointment-system-91352.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ZLV8KvjVy8uqaqlYSacpGH_1r_evu-k',
    appId: '1:1063253896672:ios:229716693be405a3538f85',
    messagingSenderId: '1063253896672',
    projectId: 'appointment-system-91352',
    storageBucket: 'appointment-system-91352.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJwpRjaNHMbSJobyG2FMpNqB1lMwqAgfI',
    appId: '1:1063253896672:web:6dbbd0283a457a74538f85',
    messagingSenderId: '1063253896672',
    projectId: 'appointment-system-91352',
    authDomain: 'appointment-system-91352.firebaseapp.com',
    storageBucket: 'appointment-system-91352.firebasestorage.app',
    measurementId: 'G-7VXP4F5YDY',
  );
}
